### ISSUE TITLE
cross-device link not permitted

### ISSUE THREAD

**Issue by MahmoudAljabary** [matootie/dokube#14]
##[error]EXDEV: cross-device link not permitted, rename '/home/runner/work/_temp/93e0c884-618d-442c-9938-ffe3f288519e' -> '/home/runner/dokubetemp/kubectl'

**Comment by matootie** [comment]
Are you using a self-hosted runner?

As far as I know, `EXDEV` is an error that Node.js throws when you try to rename files across devices. In this case, the action is attempting to rename `/home/runner/work/_temp/93e0c884-618d-442c-9938-ffe3f288519e` to `/home/runner/dokubetemp/kubectl`. This is probably happening as a result of kubectl tool being cached.. but I'm not 100% sure.

https://github.com/actions/toolkit/tree/master/packages/tool-cache#cache
https://github.com/matootie/dokube/blob/1bfdfde9318496e6be3a9687e3a671cc6a12f43b/index.js#L127

I will experiment with this and hopefully return with a solution.

**Comment by matootie** [comment]
https://github.com/matootie/dokube/commit/58cb483d6efc736131460d290a47565aeb19fb74

**Comment by matootie** [comment]
@MahmoudAljabary this should be solved now with `v1.3.1`. Please correct your workflow to use the new version.

```yaml
- name: Set up kubectl
  uses: matootie/dokube@v1.3.1
  with:
    personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
```
