### ISSUE TITLE
Set custom namespace in context

### ISSUE THREAD

**Issue by matootie** [matootie/dokube#2]
Currently, when `dokube` generates the `kubeconfig` file, it leaves the namespace at _"default"_.

Simply provide an optional GitHub Actions input for the namespace. If it was provided, use it for the context. If not, use _"default"_

### Example

`action.yml`
```yaml
# ...
inputs:
  # ...
  namespace:
    description: 'The namespace to operate on.'
    required: false
    default: 'default'
# ...
```

`index.js`
```js
// ...
const namespaceName = core.getInput("namespace", { required: true });

contexts: [
  {
    context: {
      // ...
      namespace: namespaceName,
      // ...
    },
    // ...
  }
]
// ...
```
